networks:
  production-network:
    name: production-network

services:
  manager:
    container_name: manager
    volumes:
      - news_service_staticfiles:/code/backend/static/
      # Persist news articles that get created.
      - pg_conf:/etc/postgresql
      - pg_log:/var/log/postgresql
      - pg_data:/var/lib/postgresql/data
    networks:
      - production-network
    ports:
      - "8000:8000"
    build: .
    environment:
      - DJANGO_DEBUG_MODE=True
      - FCM_PUSH_NOTIFICATION_ENVIRONMENT=dev
    command: ./run-dev.sh
    restart: unless-stopped

volumes:
  pg_data:
  pg_conf:
  pg_log:
  news_service_staticfiles:
