# Generated by Django 4.0.5 on 2022-07-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_service_app', '0003_alter_newsarticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
