# Generated by Django 4.0.5 on 2022-07-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_service_app', '0004_alter_newsarticle_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='article_title',
            field=models.CharField(max_length=70),
        ),
    ]
