# Generated by Django 4.0.5 on 2022-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='md5',
            field=models.CharField(max_length=32),
        ),
    ]
